/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JFrame;
import javax.swing.JButton;

/**
 *
 * @author dudak_ondrej
 */
public class HraciPole extends javax.swing.JFrame {

    private final int VELIKOST = 600;
    private Hra hra;

    /**
     * Creates new form HraciPole
     */
    public HraciPole() {
        initComponents();
        this.hra = new Hra(this);
        svet.setLayout(new GridLayout(9, 9));
        for (int r = 0; r < 9; r++) {
            for (int s = 0; s < 9; s++) {
                svet.add(hra.getPolicko(r, s));
                hra.getPolicko(r, s).addPropertyChangeListener(new PropertyChangeListener() {
                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        chyby.setText("Chyby " + hra.vratPocetChyb() + " / 3");
                        
                        if(hra.getKonec())
                            return;
                        
                        if ((evt).getNewValue().equals(" ")) {
                            ((JButton) evt.getSource()).setText("");
                        }
                        //KONTROPLA KONEC HRY
                        hra.prohra();
                        hra.vyhralJsem();
                        //kONTROLA VYHRY

                    }
                });
                if (hra.getPolicko(r, s).isShow()) {
                    hra.getPolicko(r, s).setText(hra.getPolicko(r, s).getNumber() + "");

                }
            }
        }

        Dimension d = new Dimension(VELIKOST, VELIKOST);
        svet.setPreferredSize(d);
        pack();
        svet.revalidate();
        svet.repaint();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public javax.swing.JLabel getChyby() {
        return this.chyby;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chyby = new javax.swing.JLabel();
        svet = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chyby.setText("chyby");
        getContentPane().add(chyby, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout svetLayout = new javax.swing.GroupLayout(svet);
        svet.setLayout(svetLayout);
        svetLayout.setHorizontalGroup(
            svetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        svetLayout.setVerticalGroup(
            svetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        getContentPane().add(svet, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HraciPole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HraciPole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HraciPole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HraciPole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HraciPole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chyby;
    private javax.swing.JPanel svet;
    // End of variables declaration//GEN-END:variables

}
